name: Tencent Kubernetes Engine

on: push

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Build
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.TKE_IMAGE_URL }}:latest .

      - name: Login TKE Registry
        run: |
          echo '${{ secrets.TKE_REGISTRY_PASSWORD }}' | docker login --username=${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }} ${{ secrets.TKE_IMAGE_URL }} --password-stdin
      # Push the Docker image to TKE Registry
      - name: Publish
        run: |
          docker push ${{ secrets.TKE_IMAGE_URL }}:latest
      - name: restart deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ubectl rollout restart deployment/${{ secrets.DEPLOYMENT_NAME }} -n ${{ secrets.DEPLOYMENT_NAMESPACE }}